export const API_URL = import.meta.env.VITE_API_URL;

// performance
export const SWR_NOTE_DEDUPING_INTERVAL_MINUTES = 5;
export const SWR_NOTE_LIST_REFRESH_INTERVAL_MINUTES = 1;
export const SWR_TAG_DEDUPING_INTERVAL_MINUTES = 5;
export const SWR_TAG_LIST_REFRESH_INTERVAL_MINUTES = 1;
export const SWR_USER_DEDUPING_INTERVAL_MINUTES = 5;
