export const API_URL = import.meta.env.VITE_API_URL;
export const PORT = import.meta.env.VITE_PORT;

// performance
export const SWR_NOTE_DEDUPING_INTERVAL_MINUTES = import.meta.env
	.VITE_SWR_NOTE_DEDUPING_INTERVAL_MINUTES;

export const SWR_NOTE_LIST_REFRESH_INTERVAL_MINUTES = import.meta.env
	.VITE_SWR_NOTE_LIST_REFRESH_INTERVAL_MINUTES;

export const SWR_TAG_DEDUPING_INTERVAL_MINUTES = import.meta.env
	.VITE_SWR_TAG_DEDUPING_INTERVAL_MINUTES;

export const SWR_TAG_LIST_REFRESH_INTERVAL_MINUTES = import.meta.env
	.VITE_SWR_TAG_LIST_REFRESH_INTERVAL_MINUTES;
