#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Starting code quality checks with Husky...'
npm run vitest:test
npm run storybook:test
npx lint-staged
echo 'Husky checks completed successfully!'
