name: dispatch-update-files
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ktmage/jowift-server
          event-type: update-files
